- label: "Company"
  name: "company"
  widget: "object"

  fields:
    - label: "Company Name"
      name: "name"
      widget: "string"

    - label: "Tagline"
      name: "tagline"
      widget: "string"

    - label: "Email"
      name: "email"
      widget: "string"

    - label: "WhatsApp Number"
      name: "whatsapp_number"
      widget: "string"

    - label: "Location Indonesia"
      name: "location_id"
      widget: "string"

    - label: "Location English"
      name: "location_en"
      widget: "string"

    - label: "Instagram Handle"
      name: "instagram_handle"
      widget: "string"
      required: false

    - label: "Instagram URL"
      name: "instagram_url"
      widget: "string"
      required: false

    - label: "LinkedIn Handle"
      name: "linkedin_handle"
      widget: "string"
      required: false

    - label: "LinkedIn URL"
      name: "linkedin_url"
      widget: "string"
      required: false
